test2/Controllers/AdhAccountController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using test2.Models;

namespace test2.Controllers
{
    public class AdhAccountController : Controller
    {
        // GET: AdhAccount
        BsDBEntities25 db5 = new BsDBEntities25();

        public ActionResult IndexAdh()
        {
            // Récupérer la liste des prestataires
            List<tbl_adherent> adhList = db5.tbl_adherent.ToList();

            // Sélectionner distinctement les valeurs de codePrestataire
            var distinctAdherent = adhList.Select(d => d.idAdherent).Distinct().ToList();

            // Créer une liste d'objets anonymes contenant les valeurs idPrestataire et displayText (codePrestataire)
            var adhtSelectList = distinctAdherent.Select(idAdherent => new
            {
                idAdherent = adhList.FirstOrDefault(p => p.idAdherent == idAdherent)?.idAdherent, // Récupérer l'ID correspondant au codePrestataire
                displayText = idAdherent // Utiliser le codePrestataire comme texte d'affichage
            }).ToList();

            // Créer une SelectList à partir de la liste d'objets anonymes
            ViewBag.ListOfAdh = new SelectList(adhtSelectList, "idAdherent", "displayText");
            return View();
        }

        public ActionResult AdherentDetails(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            // Récupérer les informations de l'adhérent correspondant à l'ID spécifié
            tbl_adherent adherent = db5.tbl_adherent.FirstOrDefault(a => a.idAdherent == id);
            if (adherent == null)
            {
                return HttpNotFound();
            }

            // Retourner uniquement le nom et le prénom de l'adhérent sous forme de données JSON
            return Json(new { nomAdh = adherent.nomAdh, prenomAdh = adherent.prenomAdh }, JsonRequestBehavior.AllowGet);
        }

    }
}

test2/Views/AdhAccount/IndexAdh.cshtml
@model test2.Models.Adherent
@{
    ViewBag.Title = "IndexAdh";
}

<h2>IndexAdh</h2>
<div class="form-group">
    <label for="DropDwn">  <small>Choisir un ID Adherent </small></label>
    @Html.DropDownListFor(m => m.idAdherent, ViewBag.ListOfAdh as SelectList, new { @id = "DropDwn", @class = "form-control" })


    <h2>Détails de l'Adhérent</h2>

    <div class="btn btn-primary" id="check_details">CLICK</div>

    <div class="form-group">
        <label for="NOM">Nom Adhérent:</label>
        @Html.TextBoxFor(m => m.nomAdh, new { @id = "NOM", @class = "form-control" })
    </div>
    <div class="form-group">
        <label for="PNOM">Prénom Adhérent:</label>
        @Html.TextBoxFor(m => m.prenomAdh, new { @id = "PNOM", @class = "form-control" })
    </div>
</div>

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>
    $(document).ready(function () {
        $('#check_details').click(function () {
            var selectedId = $('#DropDwn').val();
            $.ajax({
                url: '@Url.Action("AdherentDetails", "AdhAccount")',
                type: 'GET',
                data: { id: selectedId },
                success: function (result) {
                    $('#NOM').val(result.nomAdh);
                    $('#PNOM').val(result.prenomAdh);
                },
                error: function () {
                    alert('Une erreur s\'est produite lors de la récupération des détails de l\'adhérent.');
                }
            });
        });
    });
</script>